/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Checkbox from '../packages/checkbox/index.js';
import Dialog from '../packages/dialog/index.js';
import Input from '../packages/input/index.js';
import LoadMore from '../packages/load-more/index.js';
import Switch from '../packages/switch/index.js';
import Toast from '../packages/toast/index.js';

const components = [
  Button,
  Checkbox,
  Input,
  LoadMore,
  Switch
];

const install = function(Vue) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$wv = {
    showLoading: Toast.showLoading,
    hideLoading: Toast.hideToast,
    showToast: Toast.showToast,
    hideToast: Toast.hideToast,
    showDialog: Dialog.showDialog
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  Button,
  Checkbox,
  Dialog,
  Input,
  LoadMore,
  Switch,
  Toast
};
